### ISSUE TITLE
Does megablocks support the true expert parallelism?

### ISSUE THREAD

**Issue by feifeibear** [stanford-futuredata/megablocks#21]
Hello dear authors,

Thank you for contributing such a great project. It has been very helpful for my research on MoE training.

There is something I would like to double-check with you. Although there are two arguments, `moe_expert_model_parallelism` and `moe_weight_parallelism`, during dMoE initialization, their meanings seem to be somewhat confusing. According to my understanding:

`moe_expert_model_parallelism` distributes experts across different GPUs. However, if the #GPU is larger than #Expert, additional #GPU/#Expert tensor parallelism is applied.
`moe_weight_parallelism` is actually ZeRO-DP parallelism, where model parameters need to be synchronized during each training forward and backward pass.

Can moe_weight_parallelism and moe_expert_model_parallelism used together?

**Comment by tgale96** [comment]
Hi, thanks for the question! You have it correct and yes, sharded data parallelism and expert model parallelism can be used together.

**Comment by tgale96** [comment]
Closing - feel free to re-open if you have more questions!
