### ISSUE TITLE
Current installation instructions don't quite work

### ISSUE THREAD

**Issue by deepakn94** [stanford-futuredata/megablocks#3]
`docker build . -t megablocks-dev` and then `bash docker.sh` gives a docker container with the wrong version of `stanford-stk`. We also need to still run `python setup.py install` from `/mount/megablocks` to install `megablocks_ops`.

**Comment by tgale96** [comment]
Fixed ([1](https://github.com/stanford-futuredata/megablocks/commit/cd8a7fbcc26d875924d1f849bb3b2cc46e9b97fe), [2](https://github.com/stanford-futuredata/megablocks/commit/a1226898d93ea4667d5be531552c2576d1f73c26)).
