### ISSUE TITLE
Wrong outputs for hidden dim 14336

### ISSUE THREAD

**Issue by pierrestock** [stanford-futuredata/megablocks#46]
Was trying to run this: magnet:?xt=urn:btih:5546272da9065eddeb6fcd7ffddeef5b75be79a7&dn=mixtral-8x7b-32kseqlen&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%[2Ftracker.opentrackr.org](http://2ftracker.opentrackr.org/)%3A1337%2Fannounce&tr=udp%3A%2F%[2Ftracker.openbittorrent.com](http://2ftracker.openbittorrent.com/)%3A6969%2Fannounce&tr=http%3A%2F%[2Ftracker.openbittorrent.com](http://2ftracker.openbittorrent.com/)%3A80%2Fannounce&tr=https%3A%2F%[2Ftracker.gbitt.info](http://2ftracker.gbitt.info/)%3A443%2Fannounce

but the current code generates random outputs for hidden dim 14336

**Comment by tgale96** [comment]
This should be fixed now! Thanks for reporting :)

**Comment by nsaa0324** [comment]
sir, could you send this AI - program to me? i really need it. but, it is already blocked.

**Comment by DALM1** [comment]
Need it too... 👉👈
