### ISSUE TITLE
Inference code

### ISSUE THREAD

**Issue by AlpinDale** [stanford-futuredata/megablocks#48]
Hi. Is there any inference code available for dMoE models? I couldn't find any here. Thanks.

**Comment by tgale96** [comment]
Hi! We use our [Megatron-LM](https://github.com/stanford-futuredata/Megatron-LM) integration for training and inference mostly. 

I presume you're interested in the Mistral model - I'm not certain it will work with Megatron, but you could try it! Another option would be to take their 7B [reference implementation](https://github.com/mistralai/mistral-src) and replace the FFN with a dMoE layer.

**Comment by nateraw** [comment]
Unrelated to this repo, but for others coming here for mixtral inference code, you can refer to this [repo](https://github.com/dzhulgakov/llama-mistral) for now.
