### ISSUE TITLE
Latest GitHub release version higher than main branch setup.py

### ISSUE THREAD

**Issue by nateraw** [stanford-futuredata/megablocks#50]
setup.py still shows 0.4.0, while the latest release is 0.5.0

Latest PyPi release is 0.2.0.

Would be nice to have these up there as well so things are pip installable without having to do `pip install git+...` :)

**Comment by mvpatel2000** [comment]
Nice catch on version tag! Forgot to bump -- wanted to get a release out today given recent hype. Just updated.

Currently, this repo isn't super mature so we don't have bumped versions of setup.py for main branch. @tgale96 I'll let you decide if it's appropriate

I also don't know how the pypi releases happen -- @tgale96 also I'll let you take that

**Comment by tgale96** [comment]
See #32 for why I haven't updated the PyPi packages 😢 We should be able to move to Triton 2.1 but I need to test/benchmark first since Triton is a bit unstable 😁

**Comment by tgale96** [comment]
This should be fixed now :) Our PyPi packages are now v0.5.0.
