### ISSUE TITLE
Question on offsets in figures 5

### ISSUE THREAD

**Issue by DaehanKim** [stanford-futuredata/megablocks#61]
![image](https://github.com/stanford-futuredata/megablocks/assets/20675681/4bbd82b7-c484-41fb-8021-1ff962333070)

Hi! 
I appreciate Mistral team for this amazing work.
I was reading the paper and got stuck at what these offsets(row, column) mean in the figure 5.
Can you elaborate please?

Thanks!

**Comment by yaof20** [comment]
> ![image](https://private-user-images.githubusercontent.com/20675681/290396129-4bbd82b7-c484-41fb-8021-1ff962333070.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNDU1NzgsIm5iZiI6MTcyMDI0NTI3OCwicGF0aCI6Ii8yMDY3NTY4MS8yOTAzOTYxMjktNGJiZDgyYjctYzQ4NC00MWZiLTgwMjEtMWZmOTYyMzMzMDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDA1NTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OWI2YTFkY2M4YzUzMDM5ZWZhZjU2YTkzMDQwYzM5ZDUxYzNiODQ5MjRjNmMyMWMyOGRhMzViMTk1YjUyYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d6lfY_2DrLEVIzJaOlK2y4ZtjZPL9YXyKeLttiDKSLU)
> 
> Hi! I appreciate Mistral team for this amazing work. I was reading the paper and got stuck at what these offsets(row, column) mean in the figure 5. Can you elaborate please?
> 
> Thanks!

I would also suggest this blog post: https://www.geeksforgeeks.org/sparse-matrix-representations-set-3-csr/
which may be easier to understand. Hope this helps.
